catenax-ng/product-portal-backend

src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/IPortalBackendDBAccess.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/CompanyApplicationWithStatus.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalBackendDBAccess.cs
src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
src/registration/CatenaX.NetworkServices.Registration.Service/CatenaX.NetworkServices.Registration.Service.csproj
src/registration/CatenaX.NetworkServices.Registration.Service/Controllers/RegistrationController.cs
src/registration/CatenaX.NetworkServices.Registration.Service/Model/CompanyApplication.cs
src/registration/CatenaX.NetworkServices.Registration.Service/RegistrationAccess/IRegistrationDBAccess.cs
src/registration/CatenaX.NetworkServices.Registration.Service/RegistrationAccess/RegistrationDBAccess.cs

This PR implements:
https://jira.catena-x.net/browse/CPLP-621
https://jira.catena-x.net/browse/CPLP-752

CPLP-362: update and retrieve application status

---

src/mailing/CatenaX.NetworkServices.Mailing.Template/EmailTemplates/additional_user_invitation.html
src/mailing/CatenaX.NetworkServices.Mailing.Template/EmailTemplates/additional_user_invitation_with_message.html
src/mailing/CatenaX.NetworkServices.Mailing.Template/EmailTemplates/cx_admin_invitation.html
src/mailing/CatenaX.NetworkServices.Mailing.Template/EmailTemplates/nextsteps.html
src/mailing/CatenaX.NetworkServices.Mailing.Template/EmailTemplates/password.html
src/mailing/CatenaX.NetworkServices.Mailing.Template/EmailTemplates/portal_newuser_welcome.html
src/mailing/CatenaX.NetworkServices.Mailing.Template/EmailTemplates/portal_welcome_email.html
src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/appsettings.json

Email templates changes moved to new repository
Email template styles are improved
New html files for email templates are changed regarding with new styles

Feature/cax portal@cplp 596 email evaluations

---

src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/IPortalBackendDBAccess.cs

https://jira.catena-x.net/browse/CPLP-621

CPLP-362: update and retrieve application status - 2

---

src/administration/CatenaX.NetworkServices.Administration.Service/appsettings.json

https://jira.catena-x.net/browse/CPLP-583

CPLP-583 password policy and bruteforce realm config

---

README.md

README.md: Add initial content
... more content follows in future PRs

README.md: Add initial content

---

src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/CompanyWithAddress.cs

as discussed with @jjeroch : 
trivial fix changing:
shortname -> shortName
streetadditional -> streetAdditional
streetname -> streetName
streetnumber -> streetNumber
zipcode -> zipCode
in endpoints:
GET /api/registration/application/{applicationId}/companyDetailsWithAdress
POST /api/registration/application/{applicationId}/companyDetailsWithAdress
GET /api/administration/registration/application/{applicationId}/companyDetailsWithAdress

CPLP-730 fix camelcase of addressdata

---

src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/IUserBusinessLogic.cs
src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/IPortalBackendDBAccess.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/CompanyUserData.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/CompanyUserDetails.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalBackendDBAccess.cs

@oyo this PR contains the new endpoint GET /api/administration/user/owncompany/users/{companyUserId}

CPLP-912 new endpoint for userdetails of a specific user

---

src/administration/CatenaX.NetworkServices.Administration.Service/appsettings.json
src/provisioning/CatenaX.NetworkServices.Provisioning.Library/Extensions/RoleManager.cs

https://jira.catena-x.net/browse/CPLP-459

CPLP-459 appsetting and error message fix

---

src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/CompanyInvitedUser.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalBackendDBAccess.cs

https://jira.catena-x.net/browse/CPLP-459

CPLP-459 proceed to next step in case of duplicate role assignment to company_user_assigned_roles

---

.github/workflows/checkov.yml
.github/workflows/trivy.yml

https://jira.catena-x.net/browse/CPLP-975

CPLP-975: Adjust checkov and trivy workflows

---

src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/IUserBusinessLogic.cs
src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/IPortalBackendDBAccess.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/ClientRoles.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalBackendDBAccess.cs

Cplp 464 get api to show app roles

---

src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/IPortalBackendDBAccess.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalBackendDBAccess.cs
src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs

handle user creation case for already existing user

cplp -1040: handle user creation case for already existing user.

---

src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs

remove forbidden for no status update.

cplp -1022 - remove forbidden for no status update.

---

src/maintenance/CatenaX.NetworkServices.Maintenance.App/BatchDeleteService.cs

changed exitcode on success = 0 on error = 1

CPLP-1104 batch delete

---

src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/IApplicationRepository.cs

get application response changes

cplp - 1142 - get application response changes

---

src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppUserRepository.cs

fix for app user response issue and swagger documentation has been added.

cplp-1168 - fix for app user response and swagger documentation

---

.github/workflows/release.yml

https://jira.catena-x.net/browse/CPLP-1127

CPLP-1127: Add notification service to release workflow

---

.github/workflows/sonarcloud.yml
src/portalbackend/CatenaX.NetworkServices.PortalBackend.Migrations/CatenaX.NetworkServices.PortalBackend.Migrations.csproj

CPLP-1281: Sonarcloud enabling - add test coverage and exclude migrations project

---

.github/workflows/sonarcloud.yml

Sonarcloud - enable test-coverage
Successfully tested in feature branch:
https://sonarcloud.io/summary/new_code?id=catenax-ng_product-portal-backend&branch=feature%2FCPLP-1281-sonarcloud-workflow-4

CPLP-1281: Sonarcloud - enable test-coverage

---

.github/workflows/sonarcloud.yml
src/settings-coverage.xml

CPLP-1281: Sonarcloud enabling - add settings file for dotnet-coverage

---

.github/workflows/unit.tests.yml

CPLP-1281: Add unit test execution workflow

---

src/portalbackend/CatenaX.NetworkServices.PortalBackend.Migrations/Migrations/20220728080922_CPLP-1241-AddLastChangedDateToApp.Designer.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.Migrations/Migrations/20220728080922_CPLP-1241-AddLastChangedDateToApp.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/App.cs

Implementation of [CPLP-1241](https://jira.catena-x.net/browse/CPLP-1241)
Please check the [Database PR](https://github.com/tractusx-team-portal-onboarding/devenv/pull/92) as well

CPLP-1241 add DateLastChange to app

---

src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/CompanyRoleData.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/CompanyRolesRepository.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ICompanyRolesRepository.cs
src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
src/registration/CatenaX.NetworkServices.Registration.Service/Controllers/RegistrationController.cs

get company roles and description.

cplp - 1202 - get company roles and description

---

.github/workflows/administration-service.yml
.github/workflows/int-release.yml
.github/workflows/maintenance-service.yml
.github/workflows/marketplace-app-service.yml
.github/workflows/notification-service.yml
.github/workflows/portal-migrations.yml
.github/workflows/provisioning-service.yml
.github/workflows/registration-service.yml

https://jira.catena-x.net/browse/CPLP-1074

CPLP-1074: Enable auto image update -2

---

.github/workflows/int-release.yml

https://jira.catena-x.net/browse/CPLP-1074

CPLP-1074: Fix env variable

---

src/administration/CatenaX.NetworkServices.Administration.Service/CatenaX.NetworkServices.Administration.Service.csproj
src/settings-coverage.xml

https://jira.catena-x.net/browse/CPLP-1291

CPLP-1291: Add sonar coverage exclusion in proj file

---

src/mailing/CatenaX.NetworkServices.Mailing.Template/CatenaX.NetworkServices.Mailing.Template.csproj
src/maintenance/CatenaX.NetworkServices.Maintenance.App/CatenaX.NetworkServices.Maintenance.App.csproj
src/marketplace/CatenaX.NetworkServices.App.Service/CatenaX.NetworkServices.App.Service.csproj
src/notification/CatenaX.NetworkServices.Notification.Service/CatenaX.NetworkServices.Notification.Service.csproj
src/provisioning/CatenaX.NetworkServices.Provisioning.Service/CatenaX.NetworkServices.Provisioning.Service.csproj
src/registration/CatenaX.NetworkServices.Registration.Service/CatenaX.NetworkServices.Registration.Service.csproj

https://jira.catena-x.net/browse/CPLP-1291

CPLP-1291: Sonar exclusion of e-mail templates and coverage exclusion for program files

---

src/mailing/CatenaX.NetworkServices.Mailing.Template/CatenaX.NetworkServices.Mailing.Template.csproj

CPLP-1281: Exclude e-mail templates subdirectories from sonar scope

---

src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/ConnectorsController.cs
src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/RegistrationController.cs
src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/ServiceAccountController.cs
src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
src/registration/CatenaX.NetworkServices.Registration.Service/Controllers/RegistrationController.cs

Added summary for "POST/Service Account"

Swagger / Endpoint documentation update

---

src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/IServiceAccountBusinessLogic.cs
src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/ServiceAccountSettings.cs
src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/ServiceAccountController.cs
src/administration/CatenaX.NetworkServices.Administration.Service/Program.cs
src/administration/CatenaX.NetworkServices.Administration.Service/appsettings.json
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/UserRoleData.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/IUserRolesRepository.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/UserRolesRepository.cs

get all service account roles.

cplp- 1219 - get all service account roles.

---

src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/DocumentRepository.cs

Deleted documents won't be returned by getDocuments

Deleted documents aren't returned

---

src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/DocumentsBusinessLogic.cs
src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/DocumentsController.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ConsentRepository.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/DocumentRepository.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/IConsentRepository.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/IDocumentRepository.cs

Fixed the document delete endpoint

DocumentDelete refactored

---

src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/CompanyAssignedAppsRepository.cs

cplp-1197- search by any values

---

src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/RegistrationController.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/CompanyApplicationWithCompanyUserDetails.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/IApplicationRepository.cs

search application by company name

cplp-1289- search application by company name

---

src/registration/CatenaX.NetworkServices.Registration.Service/Model/CompanyRoleAgreementData.cs

company role agreements data model changes

cplp-1399-company role agreements data model changes

---

src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Enums/CompanyRoleId.cs

add missing enum company role id.

cplp-1399- add missing enum company role id.

---

.github/workflows/administration-service.yml
.github/workflows/maintenance-service.yml
.github/workflows/marketplace-app-service.yml
.github/workflows/notification-service.yml
.github/workflows/portal-migrations.yml
.github/workflows/provisioning-service.yml
.github/workflows/registration-service.yml

https://jira.catena-x.net/browse/CPLP-1432
Example result:
https://github.com/catenax-ng/product-portal-backend/pkgs/container/product-portal-backend_administration-service

CPLP-1432: Add latest tag at image build - necessary for trivy scan

---

src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/ICompanyDataBusinessLogic.cs
src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/CompanyDataController.cs
src/administration/CatenaX.NetworkServices.Administration.Service/Program.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/CompanyWithAddress.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/CompanyRepository.cs
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ICompanyRepository.cs
src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs

cplp-1246- get own company details.

---

src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/RegistrationSettings.cs
src/administration/CatenaX.NetworkServices.Administration.Service/appsettings.json
src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/CompanyApplicationDetails.cs

https://jira.catena-x.net/browse/CPLP-1446

CPLP-1446 refactor for documenttype

---

src/marketplace/CatenaX.NetworkServices.Apps.Service/Controllers/AppReleaseProcessController.cs

https://jira.catena-x.net/browse/CPLP-833

CPLP-833 fixed swagger comments

---

src/marketplace/CatenaX.NetworkServices.Apps.Service/Controllers/AppReleaseProcessController.cs

https://jira.catena-x.net/browse/CPLP-831

CPLP-831 fixed swagger comments

---

.github/workflows/veracode.yaml

https://jira.catena-x.net/browse/CPLP-1397

CPLP-1397: Fix veracode scans with catenax-ng package names

---

src/keycloak/Keycloak.Authentication/ControllerExtensions.cs
src/keycloak/Keycloak.Authentication/Keycloak.Authentication.csproj
src/marketplace/Offers.Library/Models/OfferServiceAutoSetupData.cs
src/marketplace/Offers.Library/Service/IOfferSetupService.cs
src/marketplace/Offers.Library/Service/IOfferSubscriptionService.cs
src/marketplace/Offers.Library/Service/OfferService.cs
src/marketplace/Offers.Library/Service/OfferSetupService.cs
src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs
src/marketplace/Services.Service/BusinessLogic/IServiceBusinessLogic.cs
src/marketplace/Services.Service/BusinessLogic/ServiceBusinessLogic.cs
src/marketplace/Services.Service/Controllers/ServicesController.cs
tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
tests/marketplace/Offers.Library.Tests/Service/OfferSetupServiceTests.cs
tests/marketplace/Offers.Library.Tests/Service/OfferSubscriptionServiceTests.cs
tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs
tests/marketplace/Services.Service.Tests/Controllers/ServiceControllerTest.cs
tests/shared/Tests.Shared/Extensions/ControllerExtensions.cs

In this PR [CPLP-1644](https://jira.catena-x.net/browse/CPLP-1644)  is solved

CPLP-1644 add authentication to autosetup call

---

src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs

https://jira.catena-x.net/browse/CPLP-1470

CPLP-1470 refactor owncompany search

---

docker/Dockerfile-maintenance-service
src/maintenance/Maintenance.App/Maintenance.App.csproj

https://jira.catena-x.net/browse/CPLP-1690

CPLP-1690: Fix for maintenance-service that continues on k8s cluster

---

CHANGELOG.md

https://jira.catena-x.net/browse/CPLP-1401

CPLP-1401: Remove 0.7.0 from changelog

---

src/administration/Administration.Service/BusinessLogic/IServiceProviderBusinessLogic.cs
src/administration/Administration.Service/BusinessLogic/ServiceProviderBusinessLogic.cs
src/administration/Administration.Service/Controllers/ServiceProviderController.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyRepository.cs
tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
tests/administration/Administration.Service.Tests/BusinessLogic/ServiceProviderBusinessLogicTest.cs
tests/administration/Administration.Service.Tests/Controllers/ServiceProviderControllerTest.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRespotitoryTests.cs
tests/shared/Tests.Shared/TestSeeds/BaseSeed.cs

With this PR [CPLP-1657](https://jira.catena-x.net/browse/CPLP-1657) is resolved.

CPLP-1657 add update service provider details endpoint

---

CHANGELOG.md

@Phil91 hatte den Bugfix zum Multi Tenant vergessen

CPLP-v0.7.0-ChangeLog-creation

---

src/registration/Registration.Service/Controllers/RegistrationController.cs

Hi @Phil91 I just need to fix the permission name for the endpoint. Is this enough or do we need changes on other areas as well?

CPLP-Fix-Registration-Get-Document-Auth-Role

---

src/administration/Administration.Service/BusinessLogic/UserRolesBusinessLogic.cs
src/portalbackend/PortalBackend.DBAccess/Models/OfferIamUserData.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
tests/administration/Administration.Service.Tests/BusinessLogic/UserBusinessLogicTests.cs

implements fix for https://jira.catena-x.net/browse/CPLP-1744

CPLP-1744 handle multiple subscriptions or app-instances when editing role-assignements

---

src/administration/Administration.Service/BusinessLogic/InvitationBusinessLogic.cs
src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
src/administration/Administration.Service/appsettings.json
src/provisioning/Provisioning.Library/Models/UserCreationInfo.cs
src/registration/Registration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
src/registration/Registration.Service/Controllers/RegistrationController.cs
tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs

implements https://jira.catena-x.net/browse/CPLP-1462

CPLP-1462: switch adminservice invite-new-user template to PortalNewUserWelcome

---

src/administration/Administration.Service/BusinessLogic/IIdentityProviderBusinessLogic.cs
src/administration/Administration.Service/BusinessLogic/IdentityProviderBusinessLogic.cs
src/administration/Administration.Service/Controllers/IdentityProviderController.cs
src/keycloak/Keycloak.Library/Models/IdentityProviders/Config.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyRepository.cs
src/provisioning/Provisioning.Library/Extensions/IdentityProviderManager.cs
src/provisioning/Provisioning.Library/IProvisioningManager.cs
src/provisioning/Provisioning.Library/ProvisioningManager.cs
src/provisioning/Provisioning.Library/Service/IUserProvisioningService.cs
src/provisioning/Provisioning.Library/Service/UserProvisioningService.cs

implements https://jira.catena-x.net/browse/CPLP-1721

CPLP-1721 add optional parameter 'displayName' to identityprovider creation

---

src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
src/administration/Administration.Service/BusinessLogic/UserUploadBusinessLogic.cs
src/mailing/Mailing.SendMail/IMailingService.cs
src/mailing/Mailing.SendMail/MailingService.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IIdentityProviderRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IdentityProviderRepository.cs
src/provisioning/Provisioning.Library/Models/CompanyNameIdpAliasData.cs
src/provisioning/Provisioning.Library/Service/IUserProvisioningService.cs
src/provisioning/Provisioning.Library/Service/UserProvisioningService.cs
tests/administration/Administration.Service.Tests/BusinessLogic/UserBusinessLogicTests.cs
tests/administration/Administration.Service.Tests/BusinessLogic/UserUploadBusinessLogicTests.cs
tests/provisioning/Provisioning.Library.Tests/UserProvisioningServiceAuxiliaryMethodsTests.cs

adding send of invite-email to endpoint
POST https://localhost:5001/api/administration/user/owncompany/identityProvider/{identityProviderId}/users

CPLP-1741 add sending of invite email to identityprovider create new user endpoint

---

src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
src/marketplace/Apps.Service/ViewModels/AppRequestModel.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs

https://jira.catena-x.net/browse/CPLP-1331

CPLP-1331-Create-App-Refactoring

---

src/administration/Administration.Service/BusinessLogic/IIdentityProviderBusinessLogic.cs
src/administration/Administration.Service/BusinessLogic/IdentityProviderBusinessLogic.cs
src/administration/Administration.Service/Controllers/IdentityProviderController.cs

implements https://jira.catena-x.net/browse/CPLP-1782

CPLP-1782 change idp-link put endpoint to create-or-update semantics

---

src/marketplace/Apps.Service/Controllers/AppsController.cs
src/marketplace/Services.Service/Controllers/ServicesController.cs
tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
tests/marketplace/Services.Service.Tests/Controllers/ServiceControllerTest.cs

This Pr resolves [CPLP-1745](https://jira.catena-x.net/browse/CPLP-1745)

CPLP-1745 endpoint cleanup

---

src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
src/provisioning/Provisioning.Library/Service/UserProvisioningService.cs
tests/provisioning/Provisioning.Library.Tests/UserProvisioningServiceCreateUsersTests.cs

implements: https://jira.catena-x.net/browse/CPLP-1798

CPLP-1798-fix-duplicate-user-detection-finding-deleted-users

---

src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
src/marketplace/Apps.Service/BusinessLogic/AppsSettings.cs
src/marketplace/Apps.Service/BusinessLogic/IAppReleaseBusinessLogic.cs
src/marketplace/Apps.Service/Controllers/AppReleaseProcessController.cs
src/marketplace/Apps.Service/appsettings.json
src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
src/portalbackend/PortalBackend.PortalEntities/Enums/NotificationTypeId.cs
tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
tests/marketplace/Apps.Service.Tests/Controllers/AppReleaseProcessControllerTest.cs

https://jira.catena-x.net/browse/CPLP-1601

CPLP-1601-app-roles-activeapp

---

src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IDocumentRepository.cs
src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs

https://jira.catena-x.net/browse/CPLP-1735

CPLP-1735 Review Comment Fix

---

src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
tests/administration/Administration.Service.Tests/BusinessLogic/UserBusinessLogicTests.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/UserRepositoryTests.cs
tests/shared/Tests.Shared/TestSeeds/BaseSeed.cs

PR resolves [CPLP-1501](https://jira.catena-x.net/browse/CPLP-1501)

CPLP-1501 add user status filter

---

src/administration/Administration.Service/appsettings.json
src/marketplace/Services.Service/appsettings.json

In this PR [CPLP-1812](https://jira.catena-x.net/browse/CPLP-1812) is resolved

CPLP-1812 change bpn claim to lowercase

---

src/administration/Administration.Service/appsettings.json
src/marketplace/Apps.Service/appsettings.json
src/marketplace/Services.Service/appsettings.json
src/registration/Registration.Service/appsettings.json

Add missing objects, present in secrets but not in appsettings.
Remove env specific urls and change to test urls.
Noticed in the course of https://jira.catena-x.net/browse/CPLP-1772

CPLP-1772: Adjust appsettings

---

src/portalbackend/PortalBackend.Migrations/Migrations/20221118061606_CPLP-1318-AuditAppSubscription.Designer.cs
src/portalbackend/PortalBackend.Migrations/Migrations/20221118061606_CPLP-1318-AuditAppSubscription.cs
src/portalbackend/PortalBackend.PortalEntities/AuditEntities/AuditAppSubscriptionDetail20221118.cs
src/portalbackend/PortalBackend.PortalEntities/Entities/AppSubscriptionDetail.cs
src/portalbackend/PortalBackend.PortalEntities/PortalDbContext.cs

https://jira.catena-x.net/browse/CPLP-1318

CPLP-1318-DBAudit-AppSubscriptionDetail

---

src/portalbackend/PortalBackend.Migrations/Migrations/20221123144540_CPLP-1601-AddAppRoleEnumToNotificationTypeId.Designer.cs
src/portalbackend/PortalBackend.Migrations/Migrations/20221123144540_CPLP-1601-AddAppRoleEnumToNotificationTypeId.cs

https://jira.catena-x.net/browse/CPLP-1601

CPLP-1601-added-migration-for-notificationenum

---

src/marketplace/Offers.Library/Models/OfferProviderResponse.cs
src/marketplace/Offers.Library/Service/OfferService.cs
src/portalbackend/PortalBackend.DBAccess/Models/OfferProviderData.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs

https://jira.catena-x.net/browse/CPLP-1816

CPLP-1816-addsalesmanagerid-refactoring

---

src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/UserRepositoryTests.cs
tests/shared/Tests.Shared/TestSeeds/BaseSeed.cs

https://jira.catena-x.net/browse/CPLP-1791

CPLP-1791-getapplication

---

src/administration/Administration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
src/administration/Administration.Service/Controllers/RegistrationController.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs

https://jira.catena-x.net/browse/CPLP-914

CPLP-914-post-company-bpn

---

src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
src/portalbackend/PortalBackend.DBAccess/Repositories/IDocumentRepository.cs
src/registration/Registration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
src/registration/Registration.Service/Controllers/RegistrationController.cs
tests/portalbackend/PortalBackend.DBAccess.Tests/DocumentRepositoryTests.cs
tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
tests/registration/Registration.Service.Tests/Controller/RegistrationControllerTest.cs

https://jira.catena-x.net/browse/CPLP-1828

CPLP-1828-registration-document-refactor
